### ISSUE TITLE
Please invite me to the GitHub Community Organization

### ISSUE THREAD

**Issue by PrafulAnand** [Opentek-Org/support#8]
### Name

Praful Anand

### Discord Username (if applicable)

Praful

### Additional Context

Already contributed my bit to Opentek so would be cool to join in :)

**Comment by AnirudhPanda** [comment]
Hey @PrafulAnand 
Can you create another issue as there was some issue in the YAML file? 
I have fixed it!

Closing this issue

Sorry for the inconvenience
